const SingleHospitals = [
    {
      continent: "Europe",
      name: "Vienna General Hospital (AKH)",
      year: '2020',
      country: 'Austria',
      image: "img/gallery/hospitals/akh_h.png",
    },
    {
      continent: "Europe",
      name: "Academic Medical Center (AMC)",
      year: '2020',
      country: 'Netherlands',
      image: "img/gallery/hospitals/amc_h.png",
    },
    {
      continent: "Europe",
      name: "University Medical Center (UMC)",
      year: '2023',
      country: 'Netherlands',
      image: "img/gallery/hospitals/amc_vumc_h.png",
    },
    {
      continent: "America",
      name: "Augusta University Hospital",
      year: '2022',
      country: 'USA',
      image: "img/gallery/hospitals/augusta_h.png",
    },
    {
      continent: "America",
      name: "Boston Children's Hospital",
      year: '2023',
      country: 'USA',
      image: "img/gallery/hospitals/bostonChildren_h.png",
    },
    {
      continent: "America",
      name: "Cleveland Clinic",
      year: '2020',
      country: 'USA',
      image: "img/gallery/hospitals/cleveland_h.png",
    },
    {
      continent: "Europe",
      name: "University Hospital Cologne",
      year: '2020',
      country: 'Germany',
      image: "img/gallery/hospitals/cologne_h.png",
    },
    {
      continent: "Europe",
      name: "University Hospital Carl Gustav Carus",
      year: '2023',
      country: 'Germany',
      image: "img/gallery/hospitals/dresden_h.png",
    },
    {
      continent: "America",
      name: "Duke University Hospital",
      year: '2020',
      country: 'USA',
      image: "img/gallery/hospitals/duke_h.png",
    },
    {
      continent: "America",
      name: "Eastern Health",
      year: '2024',
      country: 'Canada',
      image: "img/gallery/hospitals/easternHealth_h.png",
    },
    {
      continent: "America",
      name: "BWH Faulkner Hospital",
      year: '2023',
      country: 'USA',
      image: "img/gallery/hospitals/faulkner_h.png",
    },
    {
      continent: "Europe",
      name: "Ghent University Hospital",
      year: '2020',
      country: 'Belgium',
      image: "img/gallery/hospitals/ghent_h.png",
    },
    {
      continent: "Europe",
      name: "University Hospital Heidelberg",
      year: '2024',
      country: 'Germany',
      image: "img/gallery/hospitals/heidelberg_h.png",
    },
    {
      continent: "America",
      name: "The Johns Hopkins Hospital",
      year: '2023',
      country: 'USA',
      image: "img/gallery/hospitals/johnsHopkins_h.png",
    },
    {
      continent: "America",
      name: "Humber River Hospital",
      year: '2020',
      country: 'Canada',
      image: "img/gallery/hospitals/humberRiver_h.png",
    },
    {
      continent: "America",
      name: "Kingston General Hospital",
      year: '2021',
      country: 'Canada',
      image: "img/gallery/hospitals/kingston_h.png",
    },
    {
      continent: "Africa",
      name: "Kyabirwa Surgical Center",
      year: '2024',
      country: 'Uganda',
      image: "img/gallery/hospitals/kyabirwa_h.png",
    },
    {
      continent: "America",
      name: "Lenox Hill Hospital",
      year: '2022',
      country: 'USA',
      image: "img/gallery/hospitals/lenoxHill_h.png",
    },
    {
      continent: "America",
      name: "Long Island Jewish Medical Center",
      year: '2020',
      country: 'USA',
      image: "img/gallery/hospitals/longIsland_h.png",
    },
    {
      continent: "America",
      name: "Mayo Clinic",
      year: '2021',
      country: 'USA',
      image: "img/gallery/hospitals/mayo_h.png",
    },
    {
      continent: "America",
      name: "Medical College of Wisconsin",
      year: '2021',
      country: 'USA',
      image: "img/gallery/hospitals/mcw_h.png",
    },
    {
      continent: "America",
      name: "Memorial Hermann",
      year: '2024',
      country: 'USA',
      image: "img/gallery/hospitals/mh_h.png",
    },
    {
      continent: "America",
      name: "Memorial Hermann Sugar land",
      year: '2024',
      country: 'USA',
      image: "img/gallery/hospitals/mh_sugar_h.png",
    },
    {
      continent: "America",
      name: "Mount Sinai NY",
      year: '2020',
      country: 'USA',
      image: "img/gallery/hospitals/mountSinaiNY_h.png",
    },
    {
      continent: "Europe",
      name: "Natecia",
      year: '2024',
      country: 'France',
      image: "img/gallery/hospitals/natecia_h.png",
    },
    {
      continent: "America",
      name: "North York Hospital",
      year: '2023',
      country: 'Canada',
      image: "img/gallery/hospitals/northYork_h.png",
    },
    {
      continent: "America",
      name: "Orlando Health",
      year: '2023',
      country: 'USA',
      image: "img/gallery/hospitals/orlandoHealth_h.png",
    },
    {
      continent: "America",
      name: "Ottawa General Hospital",
      year: '2023',
      country: 'Canada',
      image: "img/gallery/hospitals/ottawa_h.png",
    },
    {
      continent: "America",
      name: "Parkland",
      year: '2022',
      country: 'USA',
      image: "img/gallery/hospitals/parkland_h.png",
    },
    {
      continent: "Europe",
      name: "Rigshospitalet Hospital",
      year: '2020',
      country: 'Denmark',
      image: "img/gallery/hospitals/rigshospitalet_h.png",
    },
    {
      continent: "Europe",
      name: "The Royal Infirmary of Edinburgh",
      year: '2021',
      country: 'UK',
      image: "img/gallery/hospitals/royalInfirmary_h.png",
    },
    {
      continent: "America",
      name: "The Hospital for Sick Children",
      year: '2022',
      country: 'Canada',
      image: "img/gallery/hospitals/sickkids_h.png",
    },
    {
      continent: "America",
      name: "St. Joseph's Health Centre",
      year: '2020',
      country: 'Canada',
      image: "img/gallery/hospitals/sjh_h.png",
    },
    {
      continent: "America",
      name: "St. Micheal's Hospital",
      year: '2020',
      country: 'Canada',
      image: "img/gallery/hospitals/smh_h.png",
    },
    {
      continent: "America",
      name: "Stanford Health Care",
      year: '2022',
      country: 'USA',
      image: "img/gallery/hospitals/stanford_h.png",
    },
    {
      continent: "America",
      name: "Sunnybrook Health Science Centre",
      year: '2020',
      country: 'Canada',
      image: "img/gallery/hospitals/sunnybrook_h.png",
    },
    {
      continent: "America",
      name: "Tufts Medical Center",
      year: '2022',
      country: 'USA',
      image: "img/gallery/hospitals/Tufts_h.png",
    },
    {
      continent: "America",
      name: "UC Irvine Medical Center",
      year: '2020',
      country: 'USA',
      image: "img/gallery/hospitals/ucirvine_h.png",
    },
    {
      continent: "America",
      name: "Utah Health",
      year: '2023',
      country: 'USA',
      image: "img/gallery/hospitals/UHealth_h.png",
    },
    {
      continent: "America",
      name: "UMass Memorial Health",
      year: '2021',
      country: 'USA',
      image: "img/gallery/hospitals/UMassMemorial_h.png",
    },
    {
      continent: "America",
      name: "UPenn Presbyterian",
      year: '2024',
      country: 'USA',
      image: "img/gallery/hospitals/upenn_presbyterian_h.png",
    },
    {
      continent: "America",
      name: "UT Southwestern Clements University Hospital",
      year: '2020',
      country: 'USA',
      image: "img/gallery/hospitals/utswc_h.png",
    },
    {
      continent: "America",
      name: "UT Southwestern Similation Center",
      year: '2020',
      country: 'USA',
      image: "img/gallery/hospitals/utswc_SIM_h.png",
    },
  ];
  

export default SingleHospitals;